var bzCoverageEnToZh = {
		'DamageLossCoverage' :'机动车损失险' ,
		"DamageLossExemptDeductibleSpecialClause" : '车损不计免赔率' ,
		'ThirdPartyLiabilityCoverage' : '第三者责任险' ,
		"ThirdPartyLiabilityExemptDeductibleSpecialClause" : '三责不计免赔率' ,
		'InCarDriverLiabilityCoverage' : '车上司机责任险' ,
		"InCarDriverLiabilityExemptDeductibleSpecialClause" : '车上司机责任险不计免赔率' ,
		'InCarPassengerLiabilityCoverage' : '车上乘客责任险' ,
		"InCarPassengerLiabilityExemptDeductibleSpecialClause" : '车上乘客责任险不计免赔率' ,
		'TheftCoverage' : '全车盗抢险' , 
		"TheftCoverageExemptDeductibleSpecialClause" :'盗抢不计免赔率' ,
		'GlassBrokenCoverage' :'玻璃破碎险' ,
		"SelfIgniteCoverage" : '自燃损失险' ,
		"SelfIgniteExemptDeductibleSpecialClause" : '自燃损失险不计免赔率' ,
		"NewEquipmentCoverage": '新增设备损失险' ,
		"NewEquipmentExemptDeductibleSpecialClause" :'新增设备不计免赔率' ,
		"CarBodyPaintCoverage" :'车身划痕损失险' , 
		"CarBodyPaintExemptDeductibleSpecialClause" :'车身划痕损失险不计免赔率' ,
		"PaddleDamageCoverage" :'发动机涉水损失险', 
		"PaddleDamageExemptDeductibleSpecialClause" :'发动机涉水损失险不计免赔率',
		"RepairPeriodCompensationSpecialClause" :'修理期间费用补偿险',
		"CargoInCarLiabilityCoverage":'车上货物责任险',
		"CargoInCarLiabilityExemptDeductibleSpecialClause" :'车上货物责任险不计免赔率' ,
		"SpiritDamageLiabilityCoverage" :'精神损害抚慰金责任险' ,
		"SpiritDamageLiabilityExemptDeductibleSpecialClause" :'精神损害抚慰金责任险不计免赔率' ,
		"AutoComprenhensiveDamageLossCannotFindThirdSpecialCoverage" :'车损险无法找到第三方特约险' ,
		"AppointedRepairFactorySpecialClause" :'指定修理厂险' 
}
var bzCoverageZhToEn = {
		'机动车损失险' : 'DamageLossCoverage' ,
		 '车损不计免赔率': "DamageLossExemptDeductibleSpecialClause" ,
		 '第三者责任险': 'ThirdPartyLiabilityCoverage' ,
		 '三责不计免赔率' :"ThirdPartyLiabilityExemptDeductibleSpecialClause" ,
		 '车上司机责任险':'InCarDriverLiabilityCoverage'  ,
		 '车上司机责任险不计免赔率':"InCarDriverLiabilityExemptDeductibleSpecialClause"  ,
		'车上乘客责任险': 'InCarPassengerLiabilityCoverage'  ,
		 '车上乘客责任险不计免赔率': "InCarPassengerLiabilityExemptDeductibleSpecialClause" ,
		'全车盗抢险': 'TheftCoverage'  , 
		'盗抢不计免赔率' :"TheftCoverageExemptDeductibleSpecialClause" ,
		'玻璃破碎险': 'GlassBrokenCoverage' ,
		'自燃损失险' :"SelfIgniteCoverage"  ,
		 '自燃损失险不计免赔率':"SelfIgniteExemptDeductibleSpecialClause"  ,
		 '新增设备损失险': "NewEquipmentCoverage",
		'新增设备不计免赔率':"NewEquipmentExemptDeductibleSpecialClause"  ,
		'车身划痕损失险': "CarBodyPaintCoverage" , 
		'车身划痕损失险不计免赔率': "CarBodyPaintExemptDeductibleSpecialClause" ,
		'发动机涉水损失险':"PaddleDamageCoverage" , 
		'发动机涉水损失险不计免赔率':"PaddleDamageExemptDeductibleSpecialClause" ,
		'修理期间费用补偿险' :"RepairPeriodCompensationSpecialClause" ,
		'车上货物责任险':"CargoInCarLiabilityCoverage",
		'车上货物责任险不计免赔率' :"CargoInCarLiabilityExemptDeductibleSpecialClause" ,
		'精神损害抚慰金责任险' :"SpiritDamageLiabilityCoverage" ,
		'精神损害抚慰金责任险不计免赔率': "SpiritDamageLiabilityExemptDeductibleSpecialClause" ,
		'车损险无法找到第三方特约险':"AutoComprenhensiveDamageLossCannotFindThirdSpecialCoverage"  ,
		'指定修理厂险' : "AppointedRepairFactorySpecialClause" 
}
